name = "shy-disk-b6d8"
main = "index.js"
compatibility_date = "2025-11-01"
compatibility_flags = ["nodejs_compat"]

[observability]
[observability.logs]
enabled = true
head_sampling_rate = 1
invocation_logs = true
persist = true